name: Deployment Pipeline

on:
  # will kick off a build on any push to the following patterns. If it's a non-main branch then only tests will run
  push:
    branches:
      - 'main'
      - 'develop'
      - 'feature/**'
      # - 'fix/**'
      # - 'hotfix/**'
  # to kick off manually
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version corresponding to the tag you wish to deploy (eg. v1.0.99011924)'
        required: true
        type: string
      deploy-directly-to-prod:
        description: |
          Set to true if you would like to deploy directly to PROD in an emergency situation.
          Subject to environment deployment protections
        required: false
        type: boolean
        default: false
  # for running tests when a PR is created
  pull_request:
    types:
      - opened
    branches:
      # - 'main'
      - 'develop'
jobs:
  Mule-Pipeline:
    uses: betheluniversity/mulesoft-shared-workflows/.github/workflows/mule-main.yml@feature/init-workflows
    secrets: inherit
    with:
      tag-name: ${{ inputs.tag-name }}
      anypoint-org-name: 'AVIO Sandbox'
      non-prod-env: 'DEV'
      prod-env: 'PROD'
      # optional can be removed or provide '' if nothing
      mule-deploy-args: ''